In [1]:
%load_ext autoreload
%autoreload 2

%matplotlib inline

In [2]:
#export
from exp.nb_00 import *
import operator

def test(a,b,cmp,cname=None):
    if cname is None: cname=cmp.__name__
    assert cmp(a,b),f"{cname}:\n{a}\n{b}"

def test_eq(a,b): test(a,b,operator.eq,'==')

In [3]:
test_eq(TEST,'test')

In [4]:
import torch 
from torch import tensor

### Different types of matrix multiplication

In [5]:
a = tensor([[1,10,100],[2,20,200],[3,30,300]]); a        

tensor([[  1,  10, 100],
        [  2,  20, 200],
        [  3,  30, 300]])

In [6]:
b = tensor([[1,2,3,4],[4,5,6,7],[7,8,9,10]]); b

tensor([[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]])

**Using FOR loops**

In [7]:
def matmul1(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):
        for j in range(bc):
            for k in range(ac): #or br
                c[i,j] += a[i,k]*b[k,j]
                print(f"i:{i},j:{j},k:{k}\na:{a[i,k]},b:{b[k,j]}")
                print(c)
                print("---")
    return c

In [8]:
matmul1(a,b)

i:0,j:0,k:0
a:1,b:1
tensor([[1., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
---
i:0,j:0,k:1
a:10,b:4
tensor([[41.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]])
---
i:0,j:0,k:2
a:100,b:7
tensor([[741.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.]])
---
i:0,j:1,k:0
a:1,b:2
tensor([[741.,   2.,   0.,   0.],
        [  0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.]])
---
i:0,j:1,k:1
a:10,b:5
tensor([[741.,  52.,   0.,   0.],
        [  0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.]])
---
i:0,j:1,k:2
a:100,b:8
tensor([[741., 852.,   0.,   0.],
        [  0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.]])
---
i:0,j:2,k:0
a:1,b:3
tensor([[741., 852.,   3.,   0.],
        [  0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.]])
---
i:0,j:2,k:1
a:10,b:6
tensor([[741., 852.,  63.,   0.],
        [  0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.]])
---
i:0,j:2,k:2
a

tensor([[ 741.,  852.,  963., 1074.],
        [1482., 1704., 1926., 2148.],
        [2223., 2556., 2889., 3222.]])

**Element-wise operations**

In [9]:
def matmul2(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar,bc)
    for i in range(ar):
        for j in range(bc):
            c[i,j] = (a[i,:]*b[:,j]).sum()
            print(f"i:{i},j:{j}\na:{a[i,:]},b:{b[:,j]}")
            print(c)
            print("---")
    return c

In [10]:
matmul2(a,b)

i:0,j:0
a:tensor([  1,  10, 100]),b:tensor([1, 4, 7])
tensor([[741.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.]])
---
i:0,j:1
a:tensor([  1,  10, 100]),b:tensor([2, 5, 8])
tensor([[741., 852.,   0.,   0.],
        [  0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.]])
---
i:0,j:2
a:tensor([  1,  10, 100]),b:tensor([3, 6, 9])
tensor([[741., 852., 963.,   0.],
        [  0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.]])
---
i:0,j:3
a:tensor([  1,  10, 100]),b:tensor([ 4,  7, 10])
tensor([[ 741.,  852.,  963., 1074.],
        [   0.,    0.,    0.,    0.],
        [   0.,    0.,    0.,    0.]])
---
i:1,j:0
a:tensor([  2,  20, 200]),b:tensor([1, 4, 7])
tensor([[ 741.,  852.,  963., 1074.],
        [1482.,    0.,    0.,    0.],
        [   0.,    0.,    0.,    0.]])
---
i:1,j:1
a:tensor([  2,  20, 200]),b:tensor([2, 5, 8])
tensor([[ 741.,  852.,  963., 1074.],
        [1482., 1704.,    0.,    0.],
        [   0.,    0.,    0.,    0.]])

tensor([[ 741.,  852.,  963., 1074.],
        [1482., 1704., 1926., 2148.],
        [2223., 2556., 2889., 3222.]])

**Broadcasting**

In [11]:
a[0]

tensor([  1,  10, 100])

In [12]:
a[0,:].unsqueeze(-1)

tensor([[  1],
        [ 10],
        [100]])

In [13]:
a[0,:].unsqueeze(-1).expand_as(b)

tensor([[  1,   1,   1,   1],
        [ 10,  10,  10,  10],
        [100, 100, 100, 100]])

In [14]:
a[0,:].unsqueeze(-1).expand_as(b)*b

tensor([[   1,    2,    3,    4],
        [  40,   50,   60,   70],
        [ 700,  800,  900, 1000]])

In [15]:
(a[0,:].unsqueeze(-1).expand_as(b)*b).sum(dim=0)

tensor([ 741,  852,  963, 1074])

In [16]:
def matmul3(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar,bc)
    for i in range(ar):
        c[i] = (a[i,:].unsqueeze(-1).expand_as(b)*b).sum(dim=0)
        print(f"i:{i}")
        print(c)
    return c

In [17]:
matmul3(a,b)

i:0
tensor([[ 741.,  852.,  963., 1074.],
        [   0.,    0.,    0.,    0.],
        [   0.,    0.,    0.,    0.]])
i:1
tensor([[ 741.,  852.,  963., 1074.],
        [1482., 1704., 1926., 2148.],
        [   0.,    0.,    0.,    0.]])
i:2
tensor([[ 741.,  852.,  963., 1074.],
        [1482., 1704., 1926., 2148.],
        [2223., 2556., 2889., 3222.]])


tensor([[ 741.,  852.,  963., 1074.],
        [1482., 1704., 1926., 2148.],
        [2223., 2556., 2889., 3222.]])

**Using PyTorch matmul**

In [18]:
a.matmul(b)

tensor([[ 741,  852,  963, 1074],
        [1482, 1704, 1926, 2148],
        [2223, 2556, 2889, 3222]])